### ISSUE TITLE
how to resize rbd?

### ISSUE THREAD

**Issue by yzcy** [niusmallnan/rancher-rbd-catalog#2]
Hi Niusmallnan:
when I create a container by the rancher, the rbd only having 1Gb. does it only change it on docker-compose?

**Comment by niusmallnan** [comment]
Yes, you can define it in the compose file.
```

version: '2'
services:
  foo:
    image: nginx
    volumes:
    - bar:/var/lib/storage
volumes:
  bar:
    driver: rancher-rbd
    driver_opts:
      size: 2G   # here
      pool: rbd
```
